config:
  validation: true
  warningsAsErrors: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludeCommentStatements: true
    excludeRawStrings: true
